d/b/stable-update: Use linux_version_full to get current full version
Commit 628e147dc2be ("Cleanup remaining version settings") cleaned up
the remaining use of linux_upstream_full switching to linux_version_full
but ommited the debian/bin/stable-update script.

Importing a new stable upstream version raises now

    Traceback (most recent call last):
      File "/path/linux/./debian/bin/stable-update", line 135, in <module>
        main(*sys.argv[1:])
        ~~~~^^^^^^^^^^^^^^^
      File "/path/linux/./debian/bin/stable-update", line 58, in main
        cur_ver = cur_pkg_ver.linux_upstream_full
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    AttributeError: 'VersionLinux' object has no attribute 'linux_upstream_full'

Replace the last remaining use of linux_upstream_full with
linux_version_full.

Fixes: 628e147dc2be ("Cleanup remaining version settings")
Signed-off-by: Salvatore Bonaccorso <carnil@debian.org>